import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./styles.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Rodape";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],

})

export const metadata: Metadata = {
  title: "Economize",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={poppins.className}>
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
